### ISSUE TITLE
I didn't see a task list in that comment. Remember, a task list starts with the syntax `- [ ] ` and then the task list item. The formatting is specific! Try again with a new comment. You can copy this one if you would like to see how they look:

### ISSUE THREAD

**Issue by jefferycline1** [jefferycline1/Native-Tounges#5]
I didn't see a task list in that comment. Remember, a task list starts with the syntax `- [ ] ` and then the task list item. The formatting is specific! Try again with a new comment. You can copy this one if you would like to see how they look:

```
- [ ] Turn on GitHub Pages
- [ ] Outline my portfolio
- [ ] Introduce myself to the world
```

If you would like assistance troubleshooting, create a post on the [GitHub Community](https://github.community/t5/GitHub-Learning-Lab/bd-p/learn) board. You might also want to search for your issue to see if other people have resolved it in the past.

<hr>
<h3 align="center">Watch below your comment for my response</h3>

__Originally posted by @github-learning-lab in https://github.com/jefferycline1/Native-Tounges/issues/2#issuecomment-699607411__

**Comment by jefferycline1** [comment]
- [ ] Turn on GitHub pages
- [ ] Outline my portfolio 
- [ ] Introduce myself to the world.
